# common site information
title: Lucas Jansen
description: >-
  Hi. My name is Lucas and I am an electronic and software engineer from Cork, Ireland.

baseurl: "/"
url: "https://staticintlucas.github.io"

twitter_username: staticintlucas
github_username:  staticintlucas

permalink: pretty # remove .html from the end of URLs

theme: null # TODO separate theme into its own repo?

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
      image: /assets/img/homepage.png

collections:
  projects:
    output: true # to create a page for each project

sass:
  sourcemap: development # only generate sourcemap on dev builds

exclude: # Exclude these files from build step
  - README.md
  - LICENSE
  - LICENSE-APACHE-2.0
  - LICENSE-CC-BY-SA-4.0

# Kramdown & Rouge options
kramdown:
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true

# jekyll-seo-tag
author:
  name: Lucas Jansen
  twitter: staticintlucas

twitter:
  username: staticintlucas
  card: summary

logo: /assets/img/homepage.png

social:
  name: Lucas Jansen
  links:
    - https://twitter.com/staticintlucas
    - https://github.com/staticintlucas
    - https://www.linkedin.com/in/ljansen0/

lang: en_IE

# jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
